import type { Metadata } from "next";
import { Geist,  Staatliches, Jaro } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const staat = Staatliches({
  variable: "--font-staat",
  subsets: ["latin"],
  weight:"400"
});

const jaro= Jaro({
  variable: "--font-jaro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${jaro.variable} ${staat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
